name: median_cut
description: Median Cut image color reducer using FFI
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bavagnoli.median_cut
        pluginClass: MedianCutPlugin
      ios:
        pluginClass: MedianCutPlugin
      linux:
        pluginClass: MedianCutPlugin
      web:
        pluginClass: MedianCutWeb
        fileName: median_cut_web.dart

